language: python
# in parallel, run tests in these environments
python:
    - "3.6"
    - "3.7"
# command to install dependencies
install:
    - python setup.py install

# tests to run
script:
    - python3 -c "import sbol; sbol.testSBOL()"
    - python3 -c "import sbol; sbol.testRoundTrip()"
